### ISSUE TITLE
Click close

### ISSUE THREAD

**Issue by sanyashvets** [simplesmiler/vue-clickaway#12]
I have a modal with `v-click-away` directive installed on it with `modalClose` event. And also I have dropdown's `<li>`, buttons with (`v-if`, `v-show` in modal) and `@click` events on it. I have no idea why, but modal fires it `modalClose` event by `click` on `li` and `buttons`. Yes, I can use `@mouseup` or `@mousedown` events instead of `@click`, but I think I have to tell u about this issue

P.S. thx for plugin. It's great!

**Comment by simplesmiler** [comment]
Hi! Thanks for the report and sorry for taking some time to answer.

Like with https://github.com/simplesmiler/vue-clickaway/issues/9, most likely your dropdown content is attached outside of the model container (e. g. attached to `<body>`). Can you provide a demo?

If that is the case, then the solution is to manually check in the away handler whether the event originated from the dropdown content.

**Comment by sanyashvets** [comment]
`click-away` fires, if dropdown installed with `v-if` directive. In all cases. All troubles like this happens only with `v-if`

**Comment by ExileLee** [comment]
@sanyashvets 
have same issue..

I found  a simple solution
just set `@click.stop`

**Comment by simplesmiler** [comment]
Looking at this with a fresh eye, this should have already been fixed in [2.1](https://github.com/simplesmiler/vue-clickaway/releases/tag/2.1.0).
Also, Vue 2.5 [slightly changed it's internals](https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#internals-change-for-nexttick) in a way that also should fix this issue.

You may only be affected by this if you are using Vue < 2.5 *and* VueClickaway < 2.1. Try updating, and if you are still being affected by this, please open a new issue with a repro.
