### ISSUE TITLE
Vue bundled twice (standalone build and runtime-only build)

### ISSUE THREAD

**Issue by antennaio** [simplesmiler/vue-clickaway#17]
Hi,

it may be a general question that's not 100% related to `vue-clickaway`, but I can't find a better place to ask it. :)

I already have the standalone Vue build installed in my project. When I install `vue-clickaway` I end up with both the standalone and runtime-only build included in the bundle. Is there any way to prevent that?

A simple way to see what I mean in practice is to use the official [Browserify Vue.js template](https://github.com/vuejs-templates/browserify):

`vue init browserify vue-browserify-template`

```
? Project name vue-browserify-template
? The version of the package 0.1.0
? Project description A Vue.js project
? Author someone <email@email.com>
? Vue build standalone
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Jasmine? No
```

`cd vue-browserify-template`

`npm install`
`npm install vue-click-away --save`

Then just import `vue-clickaway` anywhere:

`import { mixin as clickaway } from 'vue-clickaway';`

`npm run dev`

This leads to both the standalone build and runtime-only build to be included in the `build.js` file.

**Comment by ststaynov** [comment]
Was just about to ask the same thing!

**Comment by ststaynov** [comment]
@simplesmiler Any feedback on this issue would be highly appreciated!

**Comment by simplesmiler** [comment]
@antennaio, @ststaynov hi there!

I suppose you have `import Vue from 'vue/dist/vue'` in your code to import standalone version? If so, then this is why you end up with both variations bundled together.

Contrary to what template recommends, it's better to use something like https://github.com/benbria/aliasify instead of importing directly from a subdirectory of a module. This way, every module that imports `vue` will get the reference to standalone variation.

In long term, `vue-clickaway` should be slightly rewritten to receive reference to Vue from the code consumer instead of importing it directly, #18.

**Comment by ststaynov** [comment]
Thanks for the fast reply! Great work on the plugin btw :)
