### ISSUE TITLE
Using for closing a Modal

### ISSUE THREAD

**Issue by eigan** [simplesmiler/vue-clickaway#8]
When I use this to close a modal, the modal will not even show.

The button that trigger showing the modal, also triggers vue-clickaway. So I have to check the event.target to make sure its not the "open modal" button. Anyone have tips to prevent this? I am not sure this is can be solved by vue-clickaway, since its not really _wrong_..

**Comment by simplesmiler** [comment]
Hi, thanks for the report. Are you using Vue 1 or Vue 2?

I was able to reproduce with Vue 2. This happens because the directive is bound before the event arrives to the top of the document (thus calling the away handler just after the modal is shown), and this has to do with tasks and microtasks.

This behavior is technically correct, but is undesirable, as it breaks a typical use case I was aiming to cover.

A user land approach to this would be to "mark" the event in the corresponding click handler, and then "recognize" this fact in the away handler. This will work in simple cases, however it's quite fragile.

Another approach is to work around this in the directive by not calling the callback within the same task the directive was bound in. This is not perfect, but it's probably the way I will do it (either with a directive modifier, or as default behavior).

**Comment by eigan** [comment]
Vue 2 (not tested with Vue 1).Thank you! 👍

**Comment by simplesmiler** [comment]
Same for Vue 1. Wonder how did I miss that :confused: 
Published as [1.2.0](https://github.com/simplesmiler/vue-clickaway/releases/tag/1.2.0) and [2.1.0](https://github.com/simplesmiler/vue-clickaway/releases/tag/2.1.0) for Vue 1 and Vue 2 correspondingly.

**Comment by eigan** [comment]
Thank you, it works great :)

**Comment by simplesmiler** [comment]
Vue 2.5 [slightly changed it's internals](https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#internals-change-for-nexttick) in a way that prevents this issue from happening. Regardless, I'm gonna leave the fix in just in case.
