### ISSUE TITLE
Modals & Tinymce

### ISSUE THREAD

**Issue by joshbenhamou** [simplesmiler/vue-clickaway#9]
Encountered an issue where the clickaway function is triggered when it should be.

Using a modal window with a tinymce editor inside. When an element from the tinymce is selected the clickaway event is triggered even though the click is still in the area of the modal.

Using Vue 2 and the latest version of tinymce

**Comment by simplesmiler** [comment]
@joshbenhamou hi, thanks for the report.

I can see this happening with dropdown menus of TinyMCE, because they are getting attached to the `body` element, and thus do not get recognized as descendants of the element you put the directive on.

It looks like TinyMCE does not provide a way to tell whether the element belongs to the editor. So I don't know any good solution, except for bumbling through the editor elements and manually checking for that.

I implemented the above, please tell me if it helps you: https://jsfiddle.net/simplesmiler/4w1cs8u3/6/

**Comment by joshbenhamou** [comment]
Hi @simplesmiler 

Thanks, that's a really nice solution but requires that the TinyMCE is defined in the same component as clickaway. Unfortunately that's not the case for me so I temporarily implemented:

```if ($(e.target).parents('.mce-container').length === 0) {
this.$emit('close');
}```

Not as neat solution as yours as its jQuery dependent. Maybe the solution is to provide any parent classes in the clickaway initialization that do not trigger the close? Alternatively, do not close on anything that's attached to the body after initialization?

**Comment by simplesmiler** [comment]
Closing, as it doesn't look like there's anything that can be done from the `vue-clickaway` side. The general approach to such an issue is to manually bail from the handler if event actually originated from the modal.
